modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "newagealexscaves"
version = "${file.jarVersion}"
displayName = "newagealexscaves"
logoFile = "newagealexscaves.png"
authors = "gallichron"
description = '''
Forge Template with ParchmentMC, KotlinForForge and Mixin
'''

[[dependencies.newagealexscaves]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.newagealexscaves]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.newagealexscaves]]
modId="alexscaves"
mandatory=true
versionRange="[1.1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.newagealexscaves]]
modId="create_new_age"
mandatory=true
versionRange="[1.1.2,)"
ordering="AFTER"
side="BOTH"
